fragment SettingsParts on Settings {
  __typename
  siteName
  logo
  logoFooter
  phoneSantanyi
  phoneCalaDor
  emailSantanyi
  emailCalaDor
  instagram
  facebook
  whatsapp
  addressSantanyi
  addressCalaDor
  googleMapsSantanyi
  googleMapsCalaDor
}

fragment NavigationParts on Navigation {
  __typename
  ctaDayPassLabelCa
  ctaDayPassLabelEs
  ctaDayPassLabelEn
  ctaDayPassLabelDe
  ctaDayPassUrl
  ctaBookLabelCa
  ctaBookLabelEs
  ctaBookLabelEn
  ctaBookLabelDe
  ctaBookUrl
  items {
    __typename
    labelCa
    labelEs
    labelEn
    labelDe
    href
  }
}

fragment HeroParts on Hero {
  __typename
  badgeCa
  badgeEs
  badgeEn
  badgeDe
  titleCa
  titleEs
  titleEn
  titleDe
  subtitleCa
  subtitleEs
  subtitleEn
  subtitleDe
  ctaPrimaryCa
  ctaPrimaryEs
  ctaPrimaryEn
  ctaPrimaryDe
  stats {
    __typename
    icon
    number
    labelCa
    labelEs
    labelEn
    labelDe
  }
  heroImage
}

fragment PreusParts on Preus {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  membershipsTitleCa
  membershipsTitleEs
  membershipsTitleEn
  membershipsTitleDe
  membershipsSubCa
  membershipsSubEs
  membershipsSubEn
  membershipsSubDe
  membershipsNoteCa
  membershipsNoteEs
  membershipsNoteEn
  membershipsNoteDe
  membershipsCtaCa
  membershipsCtaEs
  membershipsCtaEn
  membershipsCtaDe
  plans {
    __typename
    nameCa
    nameEs
    nameEn
    nameDe
    price
    period
    ageCa
    ageEs
    ageEn
    ageDe
    badgeCa
    badgeEs
    badgeEn
    badgeDe
    descCa
    descEs
    descEn
    descDe
    featuresCa
    featuresEs
    featuresEn
    featuresDe
    highlighted
  }
  extraTitleCa
  extraTitleEs
  extraTitleEn
  extraTitleDe
  extraServices {
    __typename
    nameCa
    nameEs
    nameEn
    nameDe
    price
    noteCa
    noteEs
    noteEn
    noteDe
  }
  referralTitleCa
  referralTitleEs
  referralTitleEn
  referralTitleDe
  referralDescCa
  referralDescEs
  referralDescEn
  referralDescDe
  referralCtaCa
  referralCtaEs
  referralCtaEn
  referralCtaDe
}

fragment HorarisParts on Horaris {
  __typename
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  temporada
  pdfSantanyi
  pdfCalaDor
  horaLabel
  dayLabelDl
  dayLabelDm
  dayLabelDc
  dayLabelDj
  dayLabelDv
  dayLabelDs
  dayLabelDg
  footerNoteCa
  footerNoteEs
  footerNoteEn
  footerNoteDe
  rows {
    __typename
    hora
    dilluns {
      __typename
      activitat
      logo
    }
    dimarts {
      __typename
      activitat
      logo
    }
    dimecres {
      __typename
      activitat
      logo
    }
    dijous {
      __typename
      activitat
      logo
    }
    divendres {
      __typename
      activitat
      logo
    }
    dissabte {
      __typename
      activitat
      logo
    }
    diumenge {
      __typename
      activitat
      logo
    }
  }
  rowsCalaDor {
    __typename
    hora
    dilluns {
      __typename
      activitat
      logo
    }
    dimarts {
      __typename
      activitat
      logo
    }
    dimecres {
      __typename
      activitat
      logo
    }
    dijous {
      __typename
      activitat
      logo
    }
    divendres {
      __typename
      activitat
      logo
    }
    dissabte {
      __typename
      activitat
      logo
    }
    diumenge {
      __typename
      activitat
      logo
    }
  }
}

fragment PaginaSantanyiParts on PaginaSantanyi {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroDescCa
  heroDescEs
  heroDescEn
  heroDescDe
  heroAddress
  heroPhone
  heroMapsUrl
  heroMapsLabelCa
  heroMapsLabelEs
  heroMapsLabelEn
  heroMapsLabelDe
  gallery {
    __typename
    src
    alt
    size
  }
  servicesTitleCa
  servicesTitleEs
  servicesTitleEn
  servicesTitleDe
  services {
    __typename
    icon
    titleCa
    titleEs
    titleEn
    titleDe
    descCa
    descEs
    descEn
    descDe
  }
  mapTitleCa
  mapTitleEs
  mapTitleEn
  mapTitleDe
  addressLabelCa
  addressLabelEs
  addressLabelEn
  addressLabelDe
  fullAddress
  email
  mapBtnCa
  mapBtnEs
  mapBtnEn
  mapBtnDe
}

fragment PaginaCalaDorParts on PaginaCalaDor {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroDescCa
  heroDescEs
  heroDescEn
  heroDescDe
  heroAddress
  heroPhone
  heroMapsUrl
  heroMapsLabelCa
  heroMapsLabelEs
  heroMapsLabelEn
  heroMapsLabelDe
  gallery {
    __typename
    src
    alt
    size
  }
  servicesTitleCa
  servicesTitleEs
  servicesTitleEn
  servicesTitleDe
  services {
    __typename
    icon
    titleCa
    titleEs
    titleEn
    titleDe
    descCa
    descEs
    descEn
    descDe
  }
  mapTitleCa
  mapTitleEs
  mapTitleEn
  mapTitleDe
  addressLabelCa
  addressLabelEs
  addressLabelEn
  addressLabelDe
  fullAddress
  email
  mapBtnCa
  mapBtnEs
  mapBtnEn
  mapBtnDe
  contactGallery {
    __typename
    src
    alt
  }
}

fragment GaleriaSantanyiParts on GaleriaSantanyi {
  __typename
  fotos {
    __typename
    imatge
    alt
  }
}

fragment GaleriaCalaDorParts on GaleriaCalaDor {
  __typename
  fotos {
    __typename
    imatge
    alt
  }
}

fragment TrustbarParts on Trustbar {
  __typename
  items {
    __typename
    value
    labelCa
    labelEs
    labelEn
    labelDe
    icon
  }
}

fragment ServeisParts on Serveis {
  __typename
  titleCa
  titleEs
  titleEn
  titleDe
  subtitleCa
  subtitleEs
  subtitleEn
  subtitleDe
  items {
    __typename
    titleCa
    titleEs
    titleEn
    titleDe
    descCa
    descEs
    descEn
    descDe
    href
    img
    color
  }
}

fragment PaginaDayPassParts on PaginaDayPass {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitle
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  heroDescCa
  heroDescEs
  heroDescEn
  heroDescDe
  pricePool
  pricePoolGym
  poolLabelCa
  poolLabelEs
  poolLabelEn
  poolLabelDe
  poolGymLabelCa
  poolGymLabelEs
  poolGymLabelEn
  poolGymLabelDe
  perDayCa
  perDayEs
  perDayEn
  perDayDe
  includesCa
  includesEs
  includesEn
  includesDe
  sectionTitleCa
  sectionTitleEs
  sectionTitleEn
  sectionTitleDe
  poolFeatures {
    __typename
    textCa
    textEs
    textEn
    textDe
  }
  poolGymFeatures {
    __typename
    textCa
    textEs
    textEn
    textDe
  }
  poolBtnCa
  poolBtnEs
  poolBtnEn
  poolBtnDe
  facilitiesTitleCa
  facilitiesTitleEs
  facilitiesTitleEn
  facilitiesTitleDe
  formTitleCa
  formTitleEs
  formTitleEn
  formTitleDe
  formSubtitleCa
  formSubtitleEs
  formSubtitleEn
  formSubtitleDe
}

fragment DaypassParts on Daypass {
  __typename
  badgeCa
  badgeEs
  badgeEn
  badgeDe
  titleCa
  titleEs
  titleEn
  titleDe
  subtitleCa
  subtitleEs
  subtitleEn
  subtitleDe
  pricePool
  pricePoolGym
  poolLabelCa
  poolLabelEs
  poolLabelEn
  poolLabelDe
  poolGymLabelCa
  poolGymLabelEs
  poolGymLabelEn
  poolGymLabelDe
  perDayCa
  perDayEs
  perDayEn
  perDayDe
  includesCa
  includesEs
  includesEn
  includesDe
  ctaCa
  ctaEs
  ctaEn
  ctaDe
  bannerCtaCa
  bannerCtaEs
  bannerCtaEn
  bannerCtaDe
  orCa
  orEs
  orEn
  orDe
  buttons {
    __typename
    labelCa
    labelEs
    labelEn
    labelDe
    url
    style
    external
  }
}

fragment AppPromoParts on AppPromo {
  __typename
  badgeCa
  badgeEs
  badgeEn
  badgeDe
  titleCa
  titleEs
  titleEn
  titleDe
  subtitleCa
  subtitleEs
  subtitleEn
  subtitleDe
  ctaCa
  ctaEs
  ctaEn
  ctaDe
  features {
    __typename
    textCa
    textEs
    textEn
    textDe
  }
  mockupImage
}

fragment PaginaGimnasParts on PaginaGimnas {
  __typename
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  heroCtaCa
  heroCtaEs
  heroCtaEn
  heroCtaDe
  heroCtaUrl
  trainingymTitleCa
  trainingymTitleEs
  trainingymTitleEn
  trainingymTitleDe
  trainingymSubtitleCa
  trainingymSubtitleEs
  trainingymSubtitleEn
  trainingymSubtitleDe
  trainingymImage
  trainingymFeatures {
    __typename
    textCa
    textEs
    textEn
    textDe
  }
  equipmentTitleCa
  equipmentTitleEs
  equipmentTitleEn
  equipmentTitleDe
  equipment {
    __typename
    nameCa
    nameEs
    nameEn
    nameDe
    count
    icon
  }
  ctaTitleCa
  ctaTitleEs
  ctaTitleEn
  ctaTitleDe
  ctaSubtitleCa
  ctaSubtitleEs
  ctaSubtitleEn
  ctaSubtitleDe
  ctaBtn1Ca
  ctaBtn1Es
  ctaBtn1En
  ctaBtn1De
  ctaBtn1Url
  ctaBtn2Ca
  ctaBtn2Es
  ctaBtn2En
  ctaBtn2De
  ctaBtn2Url
  scheduleNoteCa
  scheduleNoteEs
  scheduleNoteEn
  scheduleNoteDe
  scheduleLinkCa
  scheduleLinkEs
  scheduleLinkEn
  scheduleLinkDe
}

fragment PaginaNatacioParts on PaginaNatacio {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  heroCtaCa
  heroCtaEs
  heroCtaEn
  heroCtaDe
  heroCtaUrl
  heroCta2Ca
  heroCta2Es
  heroCta2En
  heroCta2De
  heroCta2Url
  whyTitleCa
  whyTitleEs
  whyTitleEn
  whyTitleDe
  whyImage
  whyGallery {
    __typename
    src
    alt
  }
  whyItems {
    __typename
    textCa
    textEs
    textEn
    textDe
  }
  coursesTitleCa
  coursesTitleEs
  coursesTitleEn
  coursesTitleDe
  coursesSubCa
  coursesSubEs
  coursesSubEn
  coursesSubDe
  coursesCtaCa
  coursesCtaEs
  coursesCtaEn
  coursesCtaDe
  coursesCtaUrl
  courses {
    __typename
    nameCa
    nameEs
    nameEn
    nameDe
    age
    max
  }
  freeTitleCa
  freeTitleEs
  freeTitleEn
  freeTitleDe
  freeDescCa
  freeDescEs
  freeDescEn
  freeDescDe
  freeCtaCa
  freeCtaEs
  freeCtaEn
  freeCtaDe
  freeCtaUrl
}

fragment PaginaActivitatsParts on PaginaActivitats {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  heroCtaCa
  heroCtaEs
  heroCtaEn
  heroCtaDe
  heroCtaUrl
  heroCta2Ca
  heroCta2Es
  heroCta2En
  heroCta2De
  heroCta2Url
  allTitleCa
  allTitleEs
  allTitleEn
  allTitleDe
  allSubCa
  allSubEs
  allSubEn
  allSubDe
  ctaTitleCa
  ctaTitleEs
  ctaTitleEn
  ctaTitleDe
  ctaSubCa
  ctaSubEs
  ctaSubEn
  ctaSubDe
  ctaBtnCa
  ctaBtnEs
  ctaBtnEn
  ctaBtnDe
  ctaBtnUrl
  ctaBtn2Ca
  ctaBtn2Es
  ctaBtn2En
  ctaBtn2De
  ctaBtn2Url
  activities {
    __typename
    name
    emoji
    intensityCa
    intensityEs
    intensityEn
    intensityDe
    days
    time
    location
  }
}

fragment PaginaPadelParts on PaginaPadel {
  __typename
  heroImage
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  heroCtaCa
  heroCtaEs
  heroCtaEn
  heroCtaDe
  heroCtaUrl
  heroCta2Ca
  heroCta2Es
  heroCta2En
  heroCta2De
  heroCta2Url
  featuresTitleCa
  featuresTitleEs
  featuresTitleEn
  featuresTitleDe
  features {
    __typename
    icon
    titleCa
    titleEs
    titleEn
    titleDe
    descCa
    descEs
    descEn
    descDe
  }
  courtLabel
  courtSublabel
  playtomicLabel
  playtomicUrl
  pricingTitleCa
  pricingTitleEs
  pricingTitleEn
  pricingTitleDe
  pricingSlots {
    __typename
    labelCa
    labelEs
    labelEn
    labelDe
    hours
    price
  }
  pricingNoteCa
  pricingNoteEs
  pricingNoteEn
  pricingNoteDe
}

fragment PaginaContacteParts on PaginaContacte {
  __typename
  heroImage
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  loc1Name
  loc1Address
  loc1Phone
  loc1Email
  loc2Name
  loc2Address
  loc2Phone
  loc2Email
  followUsCa
  followUsEs
  followUsEn
  followUsDe
  instagramHandle
  instagramUrl
  instagramFollowers
  followersCa
  followersEs
  followersEn
  followersDe
  scheduleTitleCa
  scheduleTitleEs
  scheduleTitleEn
  scheduleTitleDe
  weekdaysLabelCa
  weekdaysLabelEs
  weekdaysLabelEn
  weekdaysLabelDe
  weekdaysHours
  saturdayLabelCa
  saturdayLabelEs
  saturdayLabelEn
  saturdayLabelDe
  saturdayHours
  sundayLabelCa
  sundayLabelEs
  sundayLabelEn
  sundayLabelDe
  sundayHours
  formTitleCa
  formTitleEs
  formTitleEn
  formTitleDe
  formSubtitleCa
  formSubtitleEs
  formSubtitleEn
  formSubtitleDe
  waLabelCa
  waLabelEs
  waLabelEn
  waLabelDe
  waMessageCa
  waMessageEs
  waMessageEn
  waMessageDe
}

fragment PaginesParts on Pagines {
  __typename
  seoTitleCa
  seoTitleEs
  seoTitleEn
  seoTitleDe
  seoDescCa
  seoDescEs
  seoDescEn
  seoDescDe
  heroBg
  heroBadgeCa
  heroBadgeEs
  heroBadgeEn
  heroBadgeDe
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  heroCtaCa
  heroCtaEs
  heroCtaEn
  heroCtaDe
  heroCtaUrl
  contingutCa
  contingutEs
  contingutEn
  contingutDe
  ctaTitleCa
  ctaTitleEs
  ctaTitleEn
  ctaTitleDe
  ctaBtn1Ca
  ctaBtn1Es
  ctaBtn1En
  ctaBtn1De
  ctaBtn1Url
  ctaBtn2Ca
  ctaBtn2Es
  ctaBtn2En
  ctaBtn2De
  ctaBtn2Url
}

fragment NoticiesParts on Noticies {
  __typename
  titolCa
  titolEs
  titolEn
  titolDe
  data
  imatge
  contingutCa
  contingutEs
  publicada
}

fragment PaginaNewsletterParts on PaginaNewsletter {
  __typename
  heroImage
  heroTitleCa
  heroTitleEs
  heroTitleEn
  heroTitleDe
  heroSubtitleCa
  heroSubtitleEs
  heroSubtitleEn
  heroSubtitleDe
  edicio
  imatgeDestacada
  contingutCa
  contingutEs
  contingutEn
  contingutDe
}
