// @ts-ignore
import { defineConfig } from 'tinacms';

export default defineConfig({
  branch: '',
  clientId: '',
  token: '',

  build: {
    outputFolder: 'admin',
    publicFolder: 'public',
  },

  media: {
    tina: {
      mediaRoot: 'images',
      publicFolder: 'public',
    },
  },

  schema: {
    collections: [

      // ─── CONFIGURACIÓ GENERAL ─────────────────────────────────────────
      {
        name: 'settings',
        label: '⚙️ Configuració general',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'settings' },
        fields: [
          { type: 'string', name: 'siteName',           label: 'Nom del site' },
          { type: 'image',  name: 'logo',               label: 'Logo nav',         uploadDir: () => 'public' },
          { type: 'image',  name: 'logoFooter',         label: 'Logo footer',      uploadDir: () => 'public' },
          { type: 'string', name: 'phoneSantanyi',      label: 'Telèfon Santanyí' },
          { type: 'string', name: 'phoneCalaDor',       label: "Telèfon Cala d'Or" },
          { type: 'string', name: 'emailSantanyi',      label: 'Email Santanyí' },
          { type: 'string', name: 'emailCalaDor',       label: "Email Cala d'Or" },
          { type: 'string', name: 'instagram',          label: 'Instagram URL' },
          { type: 'string', name: 'facebook',           label: 'Facebook URL' },
          { type: 'string', name: 'whatsapp',           label: 'WhatsApp (sense +)' },
          { type: 'string', name: 'addressSantanyi',    label: 'Adreça Santanyí' },
          { type: 'string', name: 'addressCalaDor',     label: "Adreça Cala d'Or" },
          { type: 'string', name: 'googleMapsSantanyi', label: 'Google Maps Santanyí' },
          { type: 'string', name: 'googleMapsCalaDor',  label: "Google Maps Cala d'Or" },
        ],
      },

      // ─── MENÚ DE NAVEGACIÓ ────────────────────────────────────────────
      {
        name: 'navigation',
        label: '🧭 Menú de navegació',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'navigation' },
        fields: [
          { type: 'string', name: 'ctaDayPassLabelCa', label: 'Botó Day Pass (CA)' },
          { type: 'string', name: 'ctaDayPassLabelEs', label: 'Botó Day Pass (ES)' },
          { type: 'string', name: 'ctaDayPassLabelEn', label: 'Botó Day Pass (EN)' },
          { type: 'string', name: 'ctaDayPassLabelDe', label: 'Botó Day Pass (DE)' },
          { type: 'string', name: 'ctaDayPassUrl',     label: 'URL Day Pass' },
          { type: 'string', name: 'ctaBookLabelCa',    label: 'Botó Reserva (CA)' },
          { type: 'string', name: 'ctaBookLabelEs',    label: 'Botó Reserva (ES)' },
          { type: 'string', name: 'ctaBookLabelEn',    label: 'Botó Reserva (EN)' },
          { type: 'string', name: 'ctaBookLabelDe',    label: 'Botó Reserva (DE)' },
          { type: 'string', name: 'ctaBookUrl',        label: 'URL Reserva' },
          {
            type: 'object',
            name: 'items',
            label: 'Elements del menú',
            list: true,
            ui: { itemProps: (item: any) => ({ label: item?.labelCa || 'Element' }) },
            fields: [
              { type: 'string', name: 'labelCa', label: 'Nom (CA)' },
              { type: 'string', name: 'labelEs', label: 'Nom (ES)' },
              { type: 'string', name: 'labelEn', label: 'Nom (EN)' },
              { type: 'string', name: 'labelDe', label: 'Nom (DE)' },
              { type: 'string', name: 'href',    label: 'URL (ex: /natacio)' },
            ],
          },
        ],
      },

      // ─── HERO PORTADA ─────────────────────────────────────────────────
      {
        name: 'hero',
        label: '🦸 Hero portada',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'hero' },
        fields: [
          { type: 'string', name: 'badgeCa',      label: 'Badge (CA)' },
          { type: 'string', name: 'badgeEs',      label: 'Badge (ES)' },
          { type: 'string', name: 'badgeEn',      label: 'Badge (EN)' },
          { type: 'string', name: 'badgeDe',      label: 'Badge (DE)' },
          { type: 'string', name: 'titleCa',      label: 'Títol (CA)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'titleEs',      label: 'Títol (ES)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'titleEn',      label: 'Títol (EN)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'titleDe',      label: 'Títol (DE)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleCa',   label: 'Subtítol (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEs',   label: 'Subtítol (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEn',   label: 'Subtítol (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleDe',   label: 'Subtítol (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'ctaPrimaryCa', label: 'Botó principal (CA)' },
          { type: 'string', name: 'ctaPrimaryEs', label: 'Botó principal (ES)' },
          { type: 'string', name: 'ctaPrimaryEn', label: 'Botó principal (EN)' },
          { type: 'string', name: 'ctaPrimaryDe', label: 'Botó principal (DE)' },
          {
            type: 'object', name: 'stats', label: 'Estadístiques', list: true,
            ui: { itemProps: (item: any) => ({ label: `${item?.icon || ''} ${item?.number || ''} ${item?.labelCa || 'Estadística'}` }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Emoji icona' },
              { type: 'string', name: 'number', label: 'Número' },
              { type: 'string', name: 'labelCa', label: 'Text (CA)' },
              { type: 'string', name: 'labelEs', label: 'Text (ES)' },
              { type: 'string', name: 'labelEn', label: 'Text (EN)' },
              { type: 'string', name: 'labelDe', label: 'Text (DE)' },
            ],
          },
          { type: 'image',  name: 'heroImage',    label: 'Foto de fons hero', uploadDir: () => 'public/images' },
        ],
      },

      // ─── PREUS ────────────────────────────────────────────────────────
      {
        name: 'preus',
        label: '💶 Preus i tarifes',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'preus' },
        fields: [
          // ── Hero ──
          { type: 'string', name: 'heroBadgeCa', label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa', label: 'Títol hero (CA)' },
          { type: 'string', name: 'heroTitleEs', label: 'Títol hero (ES)' },
          { type: 'string', name: 'heroTitleEn', label: 'Títol hero (EN)' },
          { type: 'string', name: 'heroTitleDe', label: 'Títol hero (DE)' },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)', ui: { component: 'textarea' } },
          // ── Secció abonaments ──
          { type: 'string', name: 'membershipsTitleCa', label: 'Títol abonaments (CA)' },
          { type: 'string', name: 'membershipsTitleEs', label: 'Títol abonaments (ES)' },
          { type: 'string', name: 'membershipsTitleEn', label: 'Títol abonaments (EN)' },
          { type: 'string', name: 'membershipsTitleDe', label: 'Títol abonaments (DE)' },
          { type: 'string', name: 'membershipsSubCa', label: 'Subtítol abonaments (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsSubEs', label: 'Subtítol abonaments (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsSubEn', label: 'Subtítol abonaments (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsSubDe', label: 'Subtítol abonaments (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsNoteCa', label: 'Nota abonaments (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsNoteEs', label: 'Nota abonaments (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsNoteEn', label: 'Nota abonaments (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsNoteDe', label: 'Nota abonaments (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'membershipsCtaCa', label: 'Botó abonament (CA)' },
          { type: 'string', name: 'membershipsCtaEs', label: 'Botó abonament (ES)' },
          { type: 'string', name: 'membershipsCtaEn', label: 'Botó abonament (EN)' },
          { type: 'string', name: 'membershipsCtaDe', label: 'Botó abonament (DE)' },
          {
            type: 'object',
            name: 'plans',
            label: 'Plans de preus',
            list: true,
            ui: { itemProps: (item: any) => ({ label: item?.nameCa || 'Pla' }) },
            fields: [
              { type: 'string',  name: 'nameCa',      label: 'Nom (CA)' },
              { type: 'string',  name: 'nameEs',      label: 'Nom (ES)' },
              { type: 'string',  name: 'nameEn',      label: 'Nom (EN)' },
              { type: 'string',  name: 'nameDe',      label: 'Nom (DE)' },
              { type: 'string',  name: 'price',       label: 'Preu (€)' },
              {
                type: 'string', name: 'period', label: 'Període',
                options: [
                  { label: '/mes', value: 'mes' },
                  { label: '/trimestre', value: 'trimestre' },
                  { label: '/any', value: 'any' },
                  { label: '/sessió', value: 'sessio' },
                ],
              },
              { type: 'string',  name: 'ageCa',       label: 'Edat (CA)' },
              { type: 'string',  name: 'ageEs',       label: 'Edat (ES)' },
              { type: 'string',  name: 'ageEn',       label: 'Edat (EN)' },
              { type: 'string',  name: 'ageDe',       label: 'Edat (DE)' },
              { type: 'string',  name: 'badgeCa',     label: 'Badge (CA)' },
              { type: 'string',  name: 'badgeEs',     label: 'Badge (ES)' },
              { type: 'string',  name: 'badgeEn',     label: 'Badge (EN)' },
              { type: 'string',  name: 'badgeDe',     label: 'Badge (DE)' },
              { type: 'string',  name: 'descCa',      label: 'Descripció (CA)', ui: { component: 'textarea' } },
              { type: 'string',  name: 'descEs',      label: 'Descripció (ES)', ui: { component: 'textarea' } },
              { type: 'string',  name: 'descEn',      label: 'Descripció (EN)', ui: { component: 'textarea' } },
              { type: 'string',  name: 'descDe',      label: 'Descripció (DE)', ui: { component: 'textarea' } },
              { type: 'string',  name: 'featuresCa',  label: 'Features (CA) – una per línia', list: true },
              { type: 'string',  name: 'featuresEs',  label: 'Features (ES) – una per línia', list: true },
              { type: 'string',  name: 'featuresEn',  label: 'Features (EN) – una per línia', list: true },
              { type: 'string',  name: 'featuresDe',  label: 'Features (DE) – una per línia', list: true },
              { type: 'boolean', name: 'highlighted', label: 'Destacat?' },
            ],
          },
          // ── Serveis addicionals ──
          { type: 'string', name: 'extraTitleCa', label: 'Títol serveis extra (CA)' },
          { type: 'string', name: 'extraTitleEs', label: 'Títol serveis extra (ES)' },
          { type: 'string', name: 'extraTitleEn', label: 'Títol serveis extra (EN)' },
          { type: 'string', name: 'extraTitleDe', label: 'Títol serveis extra (DE)' },
          {
            type: 'object', name: 'extraServices', label: 'Serveis addicionals', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.nameCa || 'Servei' }) },
            fields: [
              { type: 'string', name: 'nameCa', label: 'Nom (CA)' },
              { type: 'string', name: 'nameEs', label: 'Nom (ES)' },
              { type: 'string', name: 'nameEn', label: 'Nom (EN)' },
              { type: 'string', name: 'nameDe', label: 'Nom (DE)' },
              { type: 'string', name: 'price', label: 'Preu' },
              { type: 'string', name: 'noteCa', label: 'Nota (CA)' },
              { type: 'string', name: 'noteEs', label: 'Nota (ES)' },
              { type: 'string', name: 'noteEn', label: 'Nota (EN)' },
              { type: 'string', name: 'noteDe', label: 'Nota (DE)' },
            ],
          },
          // ── Referral ──
          { type: 'string', name: 'referralTitleCa', label: 'Títol referral (CA)' },
          { type: 'string', name: 'referralTitleEs', label: 'Títol referral (ES)' },
          { type: 'string', name: 'referralTitleEn', label: 'Títol referral (EN)' },
          { type: 'string', name: 'referralTitleDe', label: 'Títol referral (DE)' },
          { type: 'string', name: 'referralDescCa', label: 'Desc referral (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'referralDescEs', label: 'Desc referral (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'referralDescEn', label: 'Desc referral (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'referralDescDe', label: 'Desc referral (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'referralCtaCa', label: 'Botó referral (CA)' },
          { type: 'string', name: 'referralCtaEs', label: 'Botó referral (ES)' },
          { type: 'string', name: 'referralCtaEn', label: 'Botó referral (EN)' },
          { type: 'string', name: 'referralCtaDe', label: 'Botó referral (DE)' },
        ],
      },

      // ─── HORARIS ──────────────────────────────────────────────────────
      {
        name: 'horaris',
        label: '🗓️ Horaris',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
          router: () => '/horaris',
        },
        match: { include: 'horaris' },
        fields: [
          { type: 'string', name: 'heroTitleCa',    label: 'Títol hero (CA)' },
          { type: 'string', name: 'heroTitleEs',    label: 'Títol hero (ES)' },
          { type: 'string', name: 'heroTitleEn',    label: 'Títol hero (EN)' },
          { type: 'string', name: 'heroTitleDe',    label: 'Títol hero (DE)' },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)' },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)' },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)' },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)' },
          { type: 'string', name: 'temporada',   label: 'Temporada (ex: Hivern 2024-25)' },
          { type: 'image',  name: 'pdfSantanyi', label: 'PDF Horari Santanyí', uploadDir: () => 'public/pdfs' },
          { type: 'image',  name: 'pdfCalaDor',  label: "PDF Horari Cala d'Or", uploadDir: () => 'public/pdfs' },
          // ── Etiquetes capçalera ──
          { type: 'string', name: 'activityLabelCa', label: 'Columna Activitat (CA)' },
          { type: 'string', name: 'activityLabelEs', label: 'Columna Activitat (ES)' },
          { type: 'string', name: 'activityLabelEn', label: 'Columna Activitat (EN)' },
          { type: 'string', name: 'activityLabelDe', label: 'Columna Activitat (DE)' },
          { type: 'string', name: 'dayLabelDl', label: 'Dilluns etiqueta' },
          { type: 'string', name: 'dayLabelDm', label: 'Dimarts etiqueta' },
          { type: 'string', name: 'dayLabelDc', label: 'Dimecres etiqueta' },
          { type: 'string', name: 'dayLabelDj', label: 'Dijous etiqueta' },
          { type: 'string', name: 'dayLabelDv', label: 'Divendres etiqueta' },
          { type: 'string', name: 'dayLabelDs', label: 'Dissabte etiqueta' },
          { type: 'string', name: 'dayLabelDg', label: 'Diumenge etiqueta' },
          // ── Nota peu ──
          { type: 'string', name: 'footerNoteCa', label: 'Nota peu (CA)' },
          { type: 'string', name: 'footerNoteEs', label: 'Nota peu (ES)' },
          { type: 'string', name: 'footerNoteEn', label: 'Nota peu (EN)' },
          { type: 'string', name: 'footerNoteDe', label: 'Nota peu (DE)' },
          // ── Files horari ──
          {
            type: 'object', name: 'rows', label: "📍 Horari Santanyí", list: true,
            ui: { itemProps: (item: any) => ({ label: item?.activitat || 'Activitat' }) },
            fields: [
              { type: 'string', name: 'activitat',  label: 'Activitat' },
              { type: 'image',  name: 'logo',       label: 'Logo activitat', uploadDir: () => 'public/images/logos' },
              { type: 'string', name: 'dilluns',    label: 'Dilluns' },
              { type: 'string', name: 'dimarts',    label: 'Dimarts' },
              { type: 'string', name: 'dimecres',   label: 'Dimecres' },
              { type: 'string', name: 'dijous',     label: 'Dijous' },
              { type: 'string', name: 'divendres',  label: 'Divendres' },
              { type: 'string', name: 'dissabte',   label: 'Dissabte' },
              { type: 'string', name: 'diumenge',   label: 'Diumenge' },
            ],
          },
          {
            type: 'object', name: 'rowsCalaDor', label: "📍 Horari Cala d'Or", list: true,
            ui: { itemProps: (item: any) => ({ label: item?.activitat || 'Activitat' }) },
            fields: [
              { type: 'string', name: 'activitat',  label: 'Activitat' },
              { type: 'image',  name: 'logo',       label: 'Logo activitat', uploadDir: () => 'public/images/logos' },
              { type: 'string', name: 'dilluns',    label: 'Dilluns' },
              { type: 'string', name: 'dimarts',    label: 'Dimarts' },
              { type: 'string', name: 'dimecres',   label: 'Dimecres' },
              { type: 'string', name: 'dijous',     label: 'Dijous' },
              { type: 'string', name: 'divendres',  label: 'Divendres' },
              { type: 'string', name: 'dissabte',   label: 'Dissabte' },
              { type: 'string', name: 'diumenge',   label: 'Diumenge' },
            ],
          },
        ],
      },

      // ─── PÀGINA SANTANYÍ ──────────────────────────────────────────────
      {
        name: 'paginaSantanyi',
        label: '📍 Pàgina Santanyí',
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/santanyi' },
        match: { include: 'pagina-santanyi' },
        fields: [
          // ── Hero ──
          { type: 'string', name: 'heroBadgeCa', label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa', label: 'Títol hero (CA)' },
          { type: 'string', name: 'heroTitleEs', label: 'Títol hero (ES)' },
          { type: 'string', name: 'heroTitleEn', label: 'Títol hero (EN)' },
          { type: 'string', name: 'heroTitleDe', label: 'Títol hero (DE)' },
          { type: 'string', name: 'heroDescCa', label: 'Descripció hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescEs', label: 'Descripció hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescEn', label: 'Descripció hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescDe', label: 'Descripció hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroAddress', label: 'Adreça hero' },
          { type: 'string', name: 'heroPhone', label: 'Telèfon' },
          { type: 'string', name: 'heroMapsUrl', label: 'URL Google Maps' },
          { type: 'string', name: 'heroMapsLabelCa', label: 'Botó Maps (CA)' },
          { type: 'string', name: 'heroMapsLabelEs', label: 'Botó Maps (ES)' },
          { type: 'string', name: 'heroMapsLabelEn', label: 'Botó Maps (EN)' },
          { type: 'string', name: 'heroMapsLabelDe', label: 'Botó Maps (DE)' },
          // ── Galeria fotos ──
          {
            type: 'object', name: 'gallery', label: 'Galeria fotos', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.alt || 'Foto' }) },
            fields: [
              { type: 'image', name: 'src', label: 'Imatge', uploadDir: () => 'public/images' },
              { type: 'string', name: 'alt', label: 'Text alternatiu' },
              { type: 'string', name: 'size', label: 'Mida (large/small)', options: ['large', 'small'] },
            ],
          },
          // ── Serveis ──
          { type: 'string', name: 'servicesTitleCa', label: 'Títol serveis (CA)' },
          { type: 'string', name: 'servicesTitleEs', label: 'Títol serveis (ES)' },
          { type: 'string', name: 'servicesTitleEn', label: 'Títol serveis (EN)' },
          { type: 'string', name: 'servicesTitleDe', label: 'Títol serveis (DE)' },
          {
            type: 'object', name: 'services', label: 'Serveis', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.titleCa || 'Servei' }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Emoji' },
              { type: 'string', name: 'titleCa', label: 'Títol (CA)' },
              { type: 'string', name: 'titleEs', label: 'Títol (ES)' },
              { type: 'string', name: 'titleEn', label: 'Títol (EN)' },
              { type: 'string', name: 'titleDe', label: 'Títol (DE)' },
              { type: 'string', name: 'descCa', label: 'Descripció (CA)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEs', label: 'Descripció (ES)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEn', label: 'Descripció (EN)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descDe', label: 'Descripció (DE)', ui: { component: 'textarea' } },
            ],
          },
          // ── Contacte / mapa ──
          { type: 'string', name: 'mapTitleCa', label: 'Títol mapa (CA)' },
          { type: 'string', name: 'mapTitleEs', label: 'Títol mapa (ES)' },
          { type: 'string', name: 'mapTitleEn', label: 'Títol mapa (EN)' },
          { type: 'string', name: 'mapTitleDe', label: 'Títol mapa (DE)' },
          { type: 'string', name: 'addressLabelCa', label: 'Etiqueta adreça (CA)' },
          { type: 'string', name: 'addressLabelEs', label: 'Etiqueta adreça (ES)' },
          { type: 'string', name: 'addressLabelEn', label: 'Etiqueta adreça (EN)' },
          { type: 'string', name: 'addressLabelDe', label: 'Etiqueta adreça (DE)' },
          { type: 'string', name: 'fullAddress', label: 'Adreça completa', ui: { component: 'textarea' } },
          { type: 'string', name: 'email', label: 'Email' },
          { type: 'string', name: 'mapBtnCa', label: 'Botó Google Maps (CA)' },
          { type: 'string', name: 'mapBtnEs', label: 'Botó Google Maps (ES)' },
          { type: 'string', name: 'mapBtnEn', label: 'Botó Google Maps (EN)' },
          { type: 'string', name: 'mapBtnDe', label: 'Botó Google Maps (DE)' },
        ],
      },

      // ─── PÀGINA CALA D'OR ──────────────────────────────────────────────
      {
        name: 'paginaCalaDor',
        label: "📍 Pàgina Cala d'Or",
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/cala-dor' },
        match: { include: 'pagina-cala-dor' },
        fields: [
          // ── Hero ──
          { type: 'string', name: 'heroBadgeCa', label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa', label: 'Títol hero (CA)' },
          { type: 'string', name: 'heroTitleEs', label: 'Títol hero (ES)' },
          { type: 'string', name: 'heroTitleEn', label: 'Títol hero (EN)' },
          { type: 'string', name: 'heroTitleDe', label: 'Títol hero (DE)' },
          { type: 'string', name: 'heroDescCa', label: 'Descripció hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescEs', label: 'Descripció hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescEn', label: 'Descripció hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescDe', label: 'Descripció hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroAddress', label: 'Adreça hero' },
          { type: 'string', name: 'heroPhone', label: 'Telèfon' },
          { type: 'string', name: 'heroMapsUrl', label: 'URL Google Maps' },
          { type: 'string', name: 'heroMapsLabelCa', label: 'Botó Maps (CA)' },
          { type: 'string', name: 'heroMapsLabelEs', label: 'Botó Maps (ES)' },
          { type: 'string', name: 'heroMapsLabelEn', label: 'Botó Maps (EN)' },
          { type: 'string', name: 'heroMapsLabelDe', label: 'Botó Maps (DE)' },
          // ── Galeria fotos ──
          {
            type: 'object', name: 'gallery', label: 'Galeria fotos', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.alt || 'Foto' }) },
            fields: [
              { type: 'image', name: 'src', label: 'Imatge', uploadDir: () => 'public/images' },
              { type: 'string', name: 'alt', label: 'Text alternatiu' },
              { type: 'string', name: 'size', label: 'Mida (large/small)', options: ['large', 'small'] },
            ],
          },
          // ── Serveis ──
          { type: 'string', name: 'servicesTitleCa', label: 'Títol serveis (CA)' },
          { type: 'string', name: 'servicesTitleEs', label: 'Títol serveis (ES)' },
          { type: 'string', name: 'servicesTitleEn', label: 'Títol serveis (EN)' },
          { type: 'string', name: 'servicesTitleDe', label: 'Títol serveis (DE)' },
          {
            type: 'object', name: 'services', label: 'Serveis', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.titleCa || 'Servei' }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Emoji' },
              { type: 'string', name: 'titleCa', label: 'Títol (CA)' },
              { type: 'string', name: 'titleEs', label: 'Títol (ES)' },
              { type: 'string', name: 'titleEn', label: 'Títol (EN)' },
              { type: 'string', name: 'titleDe', label: 'Títol (DE)' },
              { type: 'string', name: 'descCa', label: 'Descripció (CA)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEs', label: 'Descripció (ES)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEn', label: 'Descripció (EN)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descDe', label: 'Descripció (DE)', ui: { component: 'textarea' } },
            ],
          },
          // ── Contacte / mapa ──
          { type: 'string', name: 'mapTitleCa', label: 'Títol mapa (CA)' },
          { type: 'string', name: 'mapTitleEs', label: 'Títol mapa (ES)' },
          { type: 'string', name: 'mapTitleEn', label: 'Títol mapa (EN)' },
          { type: 'string', name: 'mapTitleDe', label: 'Títol mapa (DE)' },
          { type: 'string', name: 'addressLabelCa', label: 'Etiqueta adreça (CA)' },
          { type: 'string', name: 'addressLabelEs', label: 'Etiqueta adreça (ES)' },
          { type: 'string', name: 'addressLabelEn', label: 'Etiqueta adreça (EN)' },
          { type: 'string', name: 'addressLabelDe', label: 'Etiqueta adreça (DE)' },
          { type: 'string', name: 'fullAddress', label: 'Adreça completa', ui: { component: 'textarea' } },
          { type: 'string', name: 'email', label: 'Email' },
          { type: 'string', name: 'mapBtnCa', label: 'Botó Google Maps (CA)' },
          { type: 'string', name: 'mapBtnEs', label: 'Botó Google Maps (ES)' },
          { type: 'string', name: 'mapBtnEn', label: 'Botó Google Maps (EN)' },
          { type: 'string', name: 'mapBtnDe', label: 'Botó Google Maps (DE)' },
          // ── Galeria contacte ──
          {
            type: 'object', name: 'contactGallery', label: 'Fotos secció contacte', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.alt || 'Foto' }) },
            fields: [
              { type: 'image', name: 'src', label: 'Imatge', uploadDir: () => 'public/images' },
              { type: 'string', name: 'alt', label: 'Text alternatiu' },
            ],
          },
        ],
      },

      // ─── GALERIA SANTANYÍ ─────────────────────────────────────────────
      {
        name: 'galeriaSantanyi',
        label: '📸 Galeria Santanyí',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'galeria-santanyi' },
        fields: [
          {
            type: 'object', name: 'fotos', label: 'Fotos', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.alt || 'Foto' }) },
            fields: [
              { type: 'image',  name: 'imatge', label: 'Foto', uploadDir: () => 'public/images' },
              { type: 'string', name: 'alt',    label: 'Descripció (alt text)' },
            ],
          },
        ],
      },

      // ─── GALERIA CALA D'OR ────────────────────────────────────────────
      {
        name: 'galeriaCalaDor',
        label: "📸 Galeria Cala d'Or",
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'galeria-cala-dor' },
        fields: [
          {
            type: 'object', name: 'fotos', label: 'Fotos', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.alt || 'Foto' }) },
            fields: [
              { type: 'image',  name: 'imatge', label: 'Foto', uploadDir: () => 'public/images' },
              { type: 'string', name: 'alt',    label: 'Descripció (alt text)' },
            ],
          },
        ],
      },

      // ─── TRUST BAR ────────────────────────────────────────────────────
      {
        name: 'trustbar',
        label: '📊 Trust Bar (xifres clau)',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'trustbar' },
        fields: [
          {
            type: 'object', name: 'items', label: 'Xifres', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.value ? `${item.value} — ${item.labelCa}` : 'Xifra' }) },
            fields: [
              { type: 'string', name: 'value',    label: 'Valor (ex: 550+)' },
              { type: 'string', name: 'labelCa',  label: 'Text (CA)' },
              { type: 'string', name: 'labelEs',  label: 'Text (ES)' },
              { type: 'string', name: 'labelEn',  label: 'Text (EN)' },
              { type: 'string', name: 'labelDe',  label: 'Text (DE)' },
              {
                type: 'string', name: 'icon', label: 'Icona',
                options: [
                  { label: 'Persones', value: 'users' },
                  { label: 'Premi', value: 'award' },
                  { label: 'Activitat', value: 'activity' },
                  { label: 'Llibre', value: 'book' },
                  { label: 'Ubicació', value: 'map-pin' },
                ],
              },
            ],
          },
        ],
      },

      // ─── SERVEIS ──────────────────────────────────────────────────────
      {
        name: 'serveis',
        label: '🏊 Serveis (grid)',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'serveis' },
        fields: [
          { type: 'string', name: 'titleCa',    label: 'Títol secció (CA)' },
          { type: 'string', name: 'titleEs',    label: 'Títol secció (ES)' },
          { type: 'string', name: 'titleEn',    label: 'Títol secció (EN)' },
          { type: 'string', name: 'titleDe',    label: 'Títol secció (DE)' },
          { type: 'string', name: 'subtitleCa', label: 'Subtítol secció (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEs', label: 'Subtítol secció (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEn', label: 'Subtítol secció (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleDe', label: 'Subtítol secció (DE)', ui: { component: 'textarea' } },
          {
            type: 'object', name: 'items', label: 'Serveis', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.titleCa || 'Servei' }) },
            fields: [
              { type: 'string', name: 'titleCa', label: 'Títol (CA)' },
              { type: 'string', name: 'titleEs', label: 'Títol (ES)' },
              { type: 'string', name: 'titleEn', label: 'Títol (EN)' },
              { type: 'string', name: 'titleDe', label: 'Títol (DE)' },
              { type: 'string', name: 'descCa',  label: 'Descripció (CA)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEs',  label: 'Descripció (ES)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEn',  label: 'Descripció (EN)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descDe',  label: 'Descripció (DE)', ui: { component: 'textarea' } },
              { type: 'string', name: 'href',    label: 'URL (ex: /natacio)' },
              { type: 'image',  name: 'img',     label: 'Icona/Imatge', uploadDir: () => 'public/images' },
              {
                type: 'string', name: 'color', label: 'Color',
                options: ['blue','purple','green','orange','red','teal'].map(c => ({ label: c, value: c })),
              },
            ],
          },
        ],
      },

      // ─── PÀGINA DAY PASS ───────────────────────────────────────────────
      {
        name: 'paginaDayPass',
        label: '🎫 Pàgina Day Pass',
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/day-pass' },
        match: { include: 'pagina-daypass' },
        fields: [
          // ── Hero ──
          { type: 'string', name: 'heroBadgeCa', label: 'Badge (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge (DE)' },
          { type: 'string', name: 'heroTitle', label: 'Títol principal' },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol (CA)' },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol (ES)' },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol (EN)' },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol (DE)' },
          { type: 'string', name: 'heroDescCa', label: 'Descripció (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescEs', label: 'Descripció (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescEn', label: 'Descripció (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroDescDe', label: 'Descripció (DE)', ui: { component: 'textarea' } },
          // ── Preus ──
          { type: 'string', name: 'pricePool', label: 'Preu Piscina (número)' },
          { type: 'string', name: 'pricePoolGym', label: 'Preu Piscina+Gimnàs (número)' },
          { type: 'string', name: 'poolLabelCa', label: 'Etiqueta piscina (CA)' },
          { type: 'string', name: 'poolLabelEs', label: 'Etiqueta piscina (ES)' },
          { type: 'string', name: 'poolLabelEn', label: 'Etiqueta piscina (EN)' },
          { type: 'string', name: 'poolLabelDe', label: 'Etiqueta piscina (DE)' },
          { type: 'string', name: 'poolGymLabelCa', label: 'Etiqueta piscina+gym (CA)' },
          { type: 'string', name: 'poolGymLabelEs', label: 'Etiqueta piscina+gym (ES)' },
          { type: 'string', name: 'poolGymLabelEn', label: 'Etiqueta piscina+gym (EN)' },
          { type: 'string', name: 'poolGymLabelDe', label: 'Etiqueta piscina+gym (DE)' },
          { type: 'string', name: 'perDayCa', label: 'Per dia (CA)' },
          { type: 'string', name: 'perDayEs', label: 'Per dia (ES)' },
          { type: 'string', name: 'perDayEn', label: 'Per dia (EN)' },
          { type: 'string', name: 'perDayDe', label: 'Per dia (DE)' },
          { type: 'string', name: 'includesCa', label: 'Inclou (CA)' },
          { type: 'string', name: 'includesEs', label: 'Inclou (ES)' },
          { type: 'string', name: 'includesEn', label: 'Inclou (EN)' },
          { type: 'string', name: 'includesDe', label: 'Inclou (DE)' },
          // ── Secció "Què inclou" ──
          { type: 'string', name: 'sectionTitleCa', label: 'Títol secció inclou (CA)' },
          { type: 'string', name: 'sectionTitleEs', label: 'Títol secció inclou (ES)' },
          { type: 'string', name: 'sectionTitleEn', label: 'Títol secció inclou (EN)' },
          { type: 'string', name: 'sectionTitleDe', label: 'Títol secció inclou (DE)' },
          {
            type: 'object', name: 'poolFeatures', label: 'Característiques Piscina', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.textCa || 'Característica' }) },
            fields: [
              { type: 'string', name: 'textCa', label: 'Text (CA)' },
              { type: 'string', name: 'textEs', label: 'Text (ES)' },
              { type: 'string', name: 'textEn', label: 'Text (EN)' },
              { type: 'string', name: 'textDe', label: 'Text (DE)' },
            ],
          },
          {
            type: 'object', name: 'poolGymFeatures', label: 'Característiques Piscina+Gym', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.textCa || 'Característica' }) },
            fields: [
              { type: 'string', name: 'textCa', label: 'Text (CA)' },
              { type: 'string', name: 'textEs', label: 'Text (ES)' },
              { type: 'string', name: 'textEn', label: 'Text (EN)' },
              { type: 'string', name: 'textDe', label: 'Text (DE)' },
            ],
          },
          { type: 'string', name: 'poolBtnCa', label: 'Botó acció (CA)' },
          { type: 'string', name: 'poolBtnEs', label: 'Botó acció (ES)' },
          { type: 'string', name: 'poolBtnEn', label: 'Botó acció (EN)' },
          { type: 'string', name: 'poolBtnDe', label: 'Botó acció (DE)' },
          // ── Instal·lacions ──
          { type: 'string', name: 'facilitiesTitleCa', label: 'Títol instal·lacions (CA)' },
          { type: 'string', name: 'facilitiesTitleEs', label: 'Títol instal·lacions (ES)' },
          { type: 'string', name: 'facilitiesTitleEn', label: 'Títol instal·lacions (EN)' },
          { type: 'string', name: 'facilitiesTitleDe', label: 'Títol instal·lacions (DE)' },
          // ── Formulari ──
          { type: 'string', name: 'formTitleCa', label: 'Títol formulari (CA)' },
          { type: 'string', name: 'formTitleEs', label: 'Títol formulari (ES)' },
          { type: 'string', name: 'formTitleEn', label: 'Títol formulari (EN)' },
          { type: 'string', name: 'formTitleDe', label: 'Títol formulari (DE)' },
          { type: 'string', name: 'formSubtitleCa', label: 'Subtítol formulari (CA)' },
          { type: 'string', name: 'formSubtitleEs', label: 'Subtítol formulari (ES)' },
          { type: 'string', name: 'formSubtitleEn', label: 'Subtítol formulari (EN)' },
          { type: 'string', name: 'formSubtitleDe', label: 'Subtítol formulari (DE)' },
        ],
      },

      // ─── DAY PASS ─────────────────────────────────────────────────────
      {
        name: 'daypass',
        label: '🎫 Day Pass CTA',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'daypass' },
        fields: [
          { type: 'string', name: 'badgeCa',       label: 'Badge (CA)' },
          { type: 'string', name: 'badgeEs',       label: 'Badge (ES)' },
          { type: 'string', name: 'badgeEn',       label: 'Badge (EN)' },
          { type: 'string', name: 'badgeDe',       label: 'Badge (DE)' },
          { type: 'string', name: 'titleCa',       label: 'Títol (CA)' },
          { type: 'string', name: 'titleEs',       label: 'Títol (ES)' },
          { type: 'string', name: 'titleEn',       label: 'Títol (EN)' },
          { type: 'string', name: 'titleDe',       label: 'Títol (DE)' },
          { type: 'string', name: 'subtitleCa',    label: 'Subtítol (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEs',    label: 'Subtítol (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEn',    label: 'Subtítol (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleDe',    label: 'Subtítol (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'pricePool',     label: 'Preu Piscina (€)' },
          { type: 'string', name: 'pricePoolGym',  label: 'Preu Piscina+Gimnàs (€)' },
          { type: 'string', name: 'poolLabelCa',   label: 'Etiqueta piscina (CA)' },
          { type: 'string', name: 'poolLabelEs',   label: 'Etiqueta piscina (ES)' },
          { type: 'string', name: 'poolLabelEn',   label: 'Etiqueta piscina (EN)' },
          { type: 'string', name: 'poolLabelDe',   label: 'Etiqueta piscina (DE)' },
          { type: 'string', name: 'poolGymLabelCa',label: 'Etiqueta piscina+gym (CA)' },
          { type: 'string', name: 'poolGymLabelEs',label: 'Etiqueta piscina+gym (ES)' },
          { type: 'string', name: 'poolGymLabelEn',label: 'Etiqueta piscina+gym (EN)' },
          { type: 'string', name: 'poolGymLabelDe',label: 'Etiqueta piscina+gym (DE)' },
          { type: 'string', name: 'perDayCa',      label: 'Per dia (CA)' },
          { type: 'string', name: 'perDayEs',      label: 'Per dia (ES)' },
          { type: 'string', name: 'perDayEn',      label: 'Per dia (EN)' },
          { type: 'string', name: 'perDayDe',      label: 'Per dia (DE)' },
          { type: 'string', name: 'includesCa',    label: 'Inclou (CA)' },
          { type: 'string', name: 'includesEs',    label: 'Inclou (ES)' },
          { type: 'string', name: 'includesEn',    label: 'Inclou (EN)' },
          { type: 'string', name: 'includesDe',    label: 'Inclou (DE)' },
          { type: 'string', name: 'ctaCa',         label: 'Botó CTA (CA)' },
          { type: 'string', name: 'ctaEs',         label: 'Botó CTA (ES)' },
          { type: 'string', name: 'ctaEn',         label: 'Botó CTA (EN)' },
          { type: 'string', name: 'ctaDe',         label: 'Botó CTA (DE)' },
          { type: 'string', name: 'bannerCtaCa',    label: 'CTA banner (CA)' },
          { type: 'string', name: 'bannerCtaEs',    label: 'CTA banner (ES)' },
          { type: 'string', name: 'bannerCtaEn',    label: 'CTA banner (EN)' },
          { type: 'string', name: 'bannerCtaDe',    label: 'CTA banner (DE)' },
          { type: 'string', name: 'orCa',          label: 'Alternativa CTA (CA)' },
          { type: 'string', name: 'orEs',          label: 'Alternativa CTA (ES)' },
          { type: 'string', name: 'orEn',          label: 'Alternativa CTA (EN)' },
          { type: 'string', name: 'orDe',          label: 'Alternativa CTA (DE)' },
          {
            type: 'object', name: 'buttons', label: '🔘 Botons addicionals', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.labelCa || 'Botó' }) },
            fields: [
              { type: 'string', name: 'labelCa', label: 'Text (CA)' },
              { type: 'string', name: 'labelEs', label: 'Text (ES)' },
              { type: 'string', name: 'labelEn', label: 'Text (EN)' },
              { type: 'string', name: 'labelDe', label: 'Text (DE)' },
              { type: 'string', name: 'url',     label: 'URL o tel: o https://' },
              {
                type: 'string', name: 'style', label: 'Estil',
                options: [
                  { label: 'Principal (blanc)', value: 'primary' },
                  { label: 'Secundari (transparent)', value: 'secondary' },
                  { label: 'Groc/Ambre', value: 'amber' },
                ],
              },
              { type: 'boolean', name: 'external', label: 'Obre en nova pestanya?' },
            ],
          },
        ],
      },

      // ─── APP PROMO ────────────────────────────────────────────────────
      {
        name: 'appPromo',
        label: '📱 App Promo',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
        },
        match: { include: 'app-promo' },
        fields: [
          { type: 'string', name: 'badgeCa',    label: 'Badge (CA)' },
          { type: 'string', name: 'badgeEs',    label: 'Badge (ES)' },
          { type: 'string', name: 'badgeEn',    label: 'Badge (EN)' },
          { type: 'string', name: 'badgeDe',    label: 'Badge (DE)' },
          { type: 'string', name: 'titleCa',    label: 'Títol (CA)' },
          { type: 'string', name: 'titleEs',    label: 'Títol (ES)' },
          { type: 'string', name: 'titleEn',    label: 'Títol (EN)' },
          { type: 'string', name: 'titleDe',    label: 'Títol (DE)' },
          { type: 'string', name: 'subtitleCa', label: 'Subtítol (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEs', label: 'Subtítol (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleEn', label: 'Subtítol (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'subtitleDe', label: 'Subtítol (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'ctaCa',      label: 'Botó App (CA)' },
          { type: 'string', name: 'ctaEs',      label: 'Botó App (ES)' },
          { type: 'string', name: 'ctaEn',      label: 'Botó App (EN)' },
          { type: 'string', name: 'ctaDe',      label: 'Botó App (DE)' },
          {
            type: 'object', name: 'features', label: 'Funcionalitats', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.textCa || 'Funcionalitat' }) },
            fields: [
              { type: 'string', name: 'textCa', label: 'Text (CA)' },
              { type: 'string', name: 'textEs', label: 'Text (ES)' },
              { type: 'string', name: 'textEn', label: 'Text (EN)' },
              { type: 'string', name: 'textDe', label: 'Text (DE)' },
            ],
          },
          { type: 'image', name: 'mockupImage', label: 'Imatge mockup app', uploadDir: () => 'public/images' },
        ],
      },

      // ─── PÀGINA GIMNÀS ────────────────────────────────────────────────
      {
        name: 'paginaGimnas',
        label: '🏋️ Pàgina Gimnàs',
        path: 'src/content',
        format: 'json',
        ui: {
          allowedActions: { create: false, delete: false },
          global: true,
          router: () => '/gimnas',
        },
        match: { include: 'pagina-gimnas' },
        fields: [
          { type: 'string', name: 'heroBadgeCa',  label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs',  label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn',  label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe',  label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa',  label: 'Títol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEs',  label: 'Títol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEn',  label: 'Títol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleDe',  label: 'Títol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroCtaCa',    label: 'CTA hero (CA)' },
          { type: 'string', name: 'heroCtaEs',    label: 'CTA hero (ES)' },
          { type: 'string', name: 'heroCtaEn',    label: 'CTA hero (EN)' },
          { type: 'string', name: 'heroCtaDe',    label: 'CTA hero (DE)' },
          { type: 'string', name: 'heroCtaUrl',   label: 'URL CTA hero' },
          { type: 'string', name: 'trainingymTitleCa',    label: 'Títol Trainingym (CA)' },
          { type: 'string', name: 'trainingymTitleEs',    label: 'Títol Trainingym (ES)' },
          { type: 'string', name: 'trainingymTitleEn',    label: 'Títol Trainingym (EN)' },
          { type: 'string', name: 'trainingymTitleDe',    label: 'Títol Trainingym (DE)' },
          { type: 'string', name: 'trainingymSubtitleCa', label: 'Text Trainingym (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'trainingymSubtitleEs', label: 'Text Trainingym (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'trainingymSubtitleEn', label: 'Text Trainingym (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'trainingymSubtitleDe', label: 'Text Trainingym (DE)', ui: { component: 'textarea' } },
          { type: 'image',  name: 'trainingymImage', label: 'Imatge Trainingym', uploadDir: () => 'public/images' },
          {
            type: 'object', name: 'trainingymFeatures', label: 'Funcionalitats Trainingym', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.textCa || 'Funcionalitat' }) },
            fields: [
              { type: 'string', name: 'textCa', label: 'Text (CA)' },
              { type: 'string', name: 'textEs', label: 'Text (ES)' },
              { type: 'string', name: 'textEn', label: 'Text (EN)' },
              { type: 'string', name: 'textDe', label: 'Text (DE)' },
            ],
          },
          { type: 'string', name: 'equipmentTitleCa', label: 'Títol equipament (CA)' },
          { type: 'string', name: 'equipmentTitleEs', label: 'Títol equipament (ES)' },
          { type: 'string', name: 'equipmentTitleEn', label: 'Títol equipament (EN)' },
          { type: 'string', name: 'equipmentTitleDe', label: 'Títol equipament (DE)' },
          {
            type: 'object', name: 'equipment', label: 'Equipament', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.nameCa || 'Equip' }) },
            fields: [
              { type: 'string', name: 'nameCa', label: 'Nom (CA)' },
              { type: 'string', name: 'nameEs', label: 'Nom (ES)' },
              { type: 'string', name: 'nameEn', label: 'Nom (EN)' },
              { type: 'string', name: 'nameDe', label: 'Nom (DE)' },
              { type: 'string', name: 'count',  label: 'Quantitat' },
              { type: 'string', name: 'icon',   label: 'Icona (emoji)' },
            ],
          },
          { type: 'string', name: 'ctaTitleCa',    label: 'Títol CTA final (CA)' },
          { type: 'string', name: 'ctaTitleEs',    label: 'Títol CTA final (ES)' },
          { type: 'string', name: 'ctaTitleEn',    label: 'Títol CTA final (EN)' },
          { type: 'string', name: 'ctaTitleDe',    label: 'Títol CTA final (DE)' },
          { type: 'string', name: 'ctaSubtitleCa', label: 'Subtítol CTA final (CA)' },
          { type: 'string', name: 'ctaSubtitleEs', label: 'Subtítol CTA final (ES)' },
          { type: 'string', name: 'ctaSubtitleEn', label: 'Subtítol CTA final (EN)' },
          { type: 'string', name: 'ctaSubtitleDe', label: 'Subtítol CTA final (DE)' },
          { type: 'string', name: 'ctaBtn1Ca',     label: 'Botó 1 (CA)' },
          { type: 'string', name: 'ctaBtn1Es',     label: 'Botó 1 (ES)' },
          { type: 'string', name: 'ctaBtn1En',     label: 'Botó 1 (EN)' },
          { type: 'string', name: 'ctaBtn1De',     label: 'Botó 1 (DE)' },
          { type: 'string', name: 'ctaBtn1Url',    label: 'URL Botó 1' },
          { type: 'string', name: 'ctaBtn2Ca',     label: 'Botó 2 (CA)' },
          { type: 'string', name: 'ctaBtn2Es',     label: 'Botó 2 (ES)' },
          { type: 'string', name: 'ctaBtn2En',     label: 'Botó 2 (EN)' },
          { type: 'string', name: 'ctaBtn2De',     label: 'Botó 2 (DE)' },
          { type: 'string', name: 'ctaBtn2Url',    label: 'URL Botó 2' },
          // ── Secció Schedule ──
          { type: 'string', name: 'scheduleNoteCa', label: 'Nota horari (CA)' },
          { type: 'string', name: 'scheduleNoteEs', label: 'Nota horari (ES)' },
          { type: 'string', name: 'scheduleNoteEn', label: 'Nota horari (EN)' },
          { type: 'string', name: 'scheduleNoteDe', label: 'Nota horari (DE)' },
          { type: 'string', name: 'scheduleLinkCa', label: 'Botó horari (CA)' },
          { type: 'string', name: 'scheduleLinkEs', label: 'Botó horari (ES)' },
          { type: 'string', name: 'scheduleLinkEn', label: 'Botó horari (EN)' },
          { type: 'string', name: 'scheduleLinkDe', label: 'Botó horari (DE)' },
        ],
      },

      // ─── PÀGINA NATACIÓ ───────────────────────────────────────────────
      {
        name: 'paginaNatacio',
        label: '🏊 Pàgina Natació',
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/natacio' },
        match: { include: 'pagina-natacio' },
        fields: [
          { type: 'string', name: 'heroBadgeCa', label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa', label: 'Títol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEs', label: 'Títol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEn', label: 'Títol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleDe', label: 'Títol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroCtaCa', label: 'CTA 1 (CA)' },
          { type: 'string', name: 'heroCtaEs', label: 'CTA 1 (ES)' },
          { type: 'string', name: 'heroCtaEn', label: 'CTA 1 (EN)' },
          { type: 'string', name: 'heroCtaDe', label: 'CTA 1 (DE)' },
          { type: 'string', name: 'heroCtaUrl', label: 'URL CTA 1' },
          { type: 'string', name: 'heroCta2Ca', label: 'CTA 2 (CA)' },
          { type: 'string', name: 'heroCta2Es', label: 'CTA 2 (ES)' },
          { type: 'string', name: 'heroCta2En', label: 'CTA 2 (EN)' },
          { type: 'string', name: 'heroCta2De', label: 'CTA 2 (DE)' },
          { type: 'string', name: 'heroCta2Url', label: 'URL CTA 2' },

          // ── Secció "Per què" ──
          { type: 'string', name: 'whyTitleCa', label: 'Títol Per què (CA)' },
          { type: 'string', name: 'whyTitleEs', label: 'Títol Per què (ES)' },
          { type: 'string', name: 'whyTitleEn', label: 'Títol Per què (EN)' },
          { type: 'string', name: 'whyTitleDe', label: 'Títol Per què (DE)' },
          { type: 'image',  name: 'whyImage',   label: 'Imatge Per què (principal)', uploadDir: () => 'public/images' },
          {
            type: 'object', name: 'whyGallery', label: 'Galeria fotos Per què', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.alt || 'Foto' }) },
            fields: [
              { type: 'image', name: 'src', label: 'Imatge', uploadDir: () => 'public/images' },
              { type: 'string', name: 'alt', label: 'Text alternatiu' },
            ],
          },
          {
            type: 'object', name: 'whyItems', label: 'Avantatges natació', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.textCa || 'Avantatge' }) },
            fields: [
              { type: 'string', name: 'textCa', label: 'Text (CA)' },
              { type: 'string', name: 'textEs', label: 'Text (ES)' },
              { type: 'string', name: 'textEn', label: 'Text (EN)' },
              { type: 'string', name: 'textDe', label: 'Text (DE)' },
            ],
          },

          // ── Secció Cursos ──
          { type: 'string', name: 'coursesTitleCa', label: 'Títol cursos (CA)' },
          { type: 'string', name: 'coursesTitleEs', label: 'Títol cursos (ES)' },
          { type: 'string', name: 'coursesTitleEn', label: 'Títol cursos (EN)' },
          { type: 'string', name: 'coursesTitleDe', label: 'Títol cursos (DE)' },
          { type: 'string', name: 'coursesSubCa', label: 'Subtítol cursos (CA)' },
          { type: 'string', name: 'coursesSubEs', label: 'Subtítol cursos (ES)' },
          { type: 'string', name: 'coursesSubEn', label: 'Subtítol cursos (EN)' },
          { type: 'string', name: 'coursesSubDe', label: 'Subtítol cursos (DE)' },
          { type: 'string', name: 'coursesCtaCa', label: 'Botó cursos (CA)' },
          { type: 'string', name: 'coursesCtaEs', label: 'Botó cursos (ES)' },
          { type: 'string', name: 'coursesCtaEn', label: 'Botó cursos (EN)' },
          { type: 'string', name: 'coursesCtaDe', label: 'Botó cursos (DE)' },
          { type: 'string', name: 'coursesCtaUrl', label: 'URL botó cursos' },
          {
            type: 'object', name: 'courses', label: 'Cursos de natació', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.nameCa || 'Curs' }) },
            fields: [
              { type: 'string', name: 'nameCa', label: 'Nivell (CA)' },
              { type: 'string', name: 'nameEs', label: 'Nivell (ES)' },
              { type: 'string', name: 'nameEn', label: 'Nivell (EN)' },
              { type: 'string', name: 'nameDe', label: 'Nivell (DE)' },
              { type: 'string', name: 'age',    label: 'Edat (ex: 6-8)' },
              { type: 'string', name: 'max',    label: 'Màx alumnes' },
            ],
          },

          // ── Secció Natació lliure ──
          { type: 'string', name: 'freeTitleCa', label: 'Títol nat. lliure (CA)' },
          { type: 'string', name: 'freeTitleEs', label: 'Títol nat. lliure (ES)' },
          { type: 'string', name: 'freeTitleEn', label: 'Títol nat. lliure (EN)' },
          { type: 'string', name: 'freeTitleDe', label: 'Títol nat. lliure (DE)' },
          { type: 'string', name: 'freeDescCa', label: 'Desc. nat. lliure (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'freeDescEs', label: 'Desc. nat. lliure (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'freeDescEn', label: 'Desc. nat. lliure (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'freeDescDe', label: 'Desc. nat. lliure (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'freeCtaCa', label: 'Botó nat. lliure (CA)' },
          { type: 'string', name: 'freeCtaEs', label: 'Botó nat. lliure (ES)' },
          { type: 'string', name: 'freeCtaEn', label: 'Botó nat. lliure (EN)' },
          { type: 'string', name: 'freeCtaDe', label: 'Botó nat. lliure (DE)' },
          { type: 'string', name: 'freeCtaUrl', label: 'URL botó nat. lliure' },
        ],
      },

      // ─── PÀGINA ACTIVITATS ────────────────────────────────────────────
      {
        name: 'paginaActivitats',
        label: '🏃 Pàgina Activitats',
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/activitats' },
        match: { include: 'pagina-activitats' },
        fields: [
          { type: 'string', name: 'heroBadgeCa', label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa', label: 'Títol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEs', label: 'Títol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEn', label: 'Títol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleDe', label: 'Títol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroCtaCa', label: 'CTA hero (CA)' },
          { type: 'string', name: 'heroCtaEs', label: 'CTA hero (ES)' },
          { type: 'string', name: 'heroCtaEn', label: 'CTA hero (EN)' },
          { type: 'string', name: 'heroCtaDe', label: 'CTA hero (DE)' },
          { type: 'string', name: 'heroCtaUrl', label: 'URL CTA hero' },
          { type: 'string', name: 'heroCta2Ca', label: 'CTA 2 hero (CA)' },
          { type: 'string', name: 'heroCta2Es', label: 'CTA 2 hero (ES)' },
          { type: 'string', name: 'heroCta2En', label: 'CTA 2 hero (EN)' },
          { type: 'string', name: 'heroCta2De', label: 'CTA 2 hero (DE)' },
          { type: 'string', name: 'heroCta2Url', label: 'URL CTA 2 hero' },
          // ── Secció llista activitats ──
          { type: 'string', name: 'allTitleCa', label: 'Títol secció activitats (CA)' },
          { type: 'string', name: 'allTitleEs', label: 'Títol secció activitats (ES)' },
          { type: 'string', name: 'allTitleEn', label: 'Títol secció activitats (EN)' },
          { type: 'string', name: 'allTitleDe', label: 'Títol secció activitats (DE)' },
          { type: 'string', name: 'allSubCa', label: 'Subtítol activitats (CA)' },
          { type: 'string', name: 'allSubEs', label: 'Subtítol activitats (ES)' },
          { type: 'string', name: 'allSubEn', label: 'Subtítol activitats (EN)' },
          { type: 'string', name: 'allSubDe', label: 'Subtítol activitats (DE)' },
          // ── Secció CTA final ──
          { type: 'string', name: 'ctaTitleCa', label: 'Títol CTA (CA)' },
          { type: 'string', name: 'ctaTitleEs', label: 'Títol CTA (ES)' },
          { type: 'string', name: 'ctaTitleEn', label: 'Títol CTA (EN)' },
          { type: 'string', name: 'ctaTitleDe', label: 'Títol CTA (DE)' },
          { type: 'string', name: 'ctaSubCa', label: 'Subtítol CTA (CA)' },
          { type: 'string', name: 'ctaSubEs', label: 'Subtítol CTA (ES)' },
          { type: 'string', name: 'ctaSubEn', label: 'Subtítol CTA (EN)' },
          { type: 'string', name: 'ctaSubDe', label: 'Subtítol CTA (DE)' },
          { type: 'string', name: 'ctaBtnCa', label: 'Botó CTA 1 (CA)' },
          { type: 'string', name: 'ctaBtnEs', label: 'Botó CTA 1 (ES)' },
          { type: 'string', name: 'ctaBtnEn', label: 'Botó CTA 1 (EN)' },
          { type: 'string', name: 'ctaBtnDe', label: 'Botó CTA 1 (DE)' },
          { type: 'string', name: 'ctaBtnUrl', label: 'URL botó CTA 1' },
          { type: 'string', name: 'ctaBtn2Ca', label: 'Botó CTA 2 (CA)' },
          { type: 'string', name: 'ctaBtn2Es', label: 'Botó CTA 2 (ES)' },
          { type: 'string', name: 'ctaBtn2En', label: 'Botó CTA 2 (EN)' },
          { type: 'string', name: 'ctaBtn2De', label: 'Botó CTA 2 (DE)' },
          { type: 'string', name: 'ctaBtn2Url', label: 'URL botó CTA 2' },
          {
            type: 'object', name: 'activities', label: 'Activitats', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.name || 'Activitat' }) },
            fields: [
              { type: 'string', name: 'name',        label: 'Nom' },
              { type: 'string', name: 'emoji',       label: 'Emoji' },
              { type: 'string', name: 'intensityCa', label: 'Intensitat (CA)' },
              { type: 'string', name: 'intensityEs', label: 'Intensitat (ES)' },
              { type: 'string', name: 'intensityEn', label: 'Intensitat (EN)' },
              { type: 'string', name: 'intensityDe', label: 'Intensitat (DE)' },
              { type: 'string', name: 'days',        label: 'Dies (ex: Dl/Dc/Dv)' },
              { type: 'string', name: 'time',        label: 'Horari (ex: 9:00–10:00)' },
              { type: 'string', name: 'location',    label: "Ubicació (ex: Santanyí + Cala d'Or)" },
            ],
          },
        ],
      },

      // ─── PÀGINA PÀDEL ─────────────────────────────────────────────────
      {
        name: 'paginaPadel',
        label: '🎾 Pàgina Pàdel',
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/padel' },
        match: { include: 'pagina-padel' },
        fields: [
          { type: 'string', name: 'heroBadgeCa', label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs', label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn', label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe', label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa', label: 'Títol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEs', label: 'Títol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEn', label: 'Títol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleDe', label: 'Títol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroCtaCa',    label: 'Botó Playtomic (CA)' },
          { type: 'string', name: 'heroCtaEs',    label: 'Botó Playtomic (ES)' },
          { type: 'string', name: 'heroCtaEn',    label: 'Botó Playtomic (EN)' },
          { type: 'string', name: 'heroCtaDe',    label: 'Botó Playtomic (DE)' },
          { type: 'string', name: 'heroCtaUrl',   label: 'URL Playtomic' },
          { type: 'string', name: 'heroCta2Ca',   label: 'Botó 2 (CA)' },
          { type: 'string', name: 'heroCta2Es',   label: 'Botó 2 (ES)' },
          { type: 'string', name: 'heroCta2En',   label: 'Botó 2 (EN)' },
          { type: 'string', name: 'heroCta2De',   label: 'Botó 2 (DE)' },
          { type: 'string', name: 'heroCta2Url',  label: 'URL botó 2' },
          // ── Secció features ──
          { type: 'string', name: 'featuresTitleCa', label: 'Títol features (CA)' },
          { type: 'string', name: 'featuresTitleEs', label: 'Títol features (ES)' },
          { type: 'string', name: 'featuresTitleEn', label: 'Títol features (EN)' },
          { type: 'string', name: 'featuresTitleDe', label: 'Títol features (DE)' },
          {
            type: 'object', name: 'features', label: 'Característiques', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.titleCa || 'Feature' }) },
            fields: [
              { type: 'string', name: 'icon', label: 'Emoji' },
              { type: 'string', name: 'titleCa', label: 'Títol (CA)' },
              { type: 'string', name: 'titleEs', label: 'Títol (ES)' },
              { type: 'string', name: 'titleEn', label: 'Títol (EN)' },
              { type: 'string', name: 'titleDe', label: 'Títol (DE)' },
              { type: 'string', name: 'descCa', label: 'Descripció (CA)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEs', label: 'Descripció (ES)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descEn', label: 'Descripció (EN)', ui: { component: 'textarea' } },
              { type: 'string', name: 'descDe', label: 'Descripció (DE)', ui: { component: 'textarea' } },
            ],
          },
          // ── Il·lustració pista ──
          { type: 'string', name: 'courtLabel', label: 'Etiqueta pista' },
          { type: 'string', name: 'courtSublabel', label: 'Subetiqueta pista' },
          { type: 'string', name: 'playtomicLabel', label: 'Botó Playtomic pista' },
          { type: 'string', name: 'playtomicUrl', label: 'URL Playtomic' },
          // ── Secció preus ──
          { type: 'string', name: 'pricingTitleCa', label: 'Títol preus (CA)' },
          { type: 'string', name: 'pricingTitleEs', label: 'Títol preus (ES)' },
          { type: 'string', name: 'pricingTitleEn', label: 'Títol preus (EN)' },
          { type: 'string', name: 'pricingTitleDe', label: 'Títol preus (DE)' },
          {
            type: 'object', name: 'pricingSlots', label: 'Franges horari/preu', list: true,
            ui: { itemProps: (item: any) => ({ label: item?.labelCa || 'Franja' }) },
            fields: [
              { type: 'string', name: 'labelCa', label: 'Franja (CA)' },
              { type: 'string', name: 'labelEs', label: 'Franja (ES)' },
              { type: 'string', name: 'labelEn', label: 'Franja (EN)' },
              { type: 'string', name: 'labelDe', label: 'Franja (DE)' },
              { type: 'string', name: 'hours', label: 'Hores' },
              { type: 'string', name: 'price', label: 'Preu' },
            ],
          },
          { type: 'string', name: 'pricingNoteCa', label: 'Nota preus (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'pricingNoteEs', label: 'Nota preus (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'pricingNoteEn', label: 'Nota preus (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'pricingNoteDe', label: 'Nota preus (DE)', ui: { component: 'textarea' } },
        ],
      },

      // ─── PÀGINA CONTACTE ──────────────────────────────────────────────
      {
        name: 'paginaContacte',
        label: '📞 Pàgina Contacte',
        path: 'src/content',
        format: 'json',
        ui: { allowedActions: { create: false, delete: false }, global: true, router: () => '/contacte' },
        match: { include: 'pagina-contacte' },
        fields: [
          { type: 'string', name: 'heroTitleCa', label: 'Títol (CA)' },
          { type: 'string', name: 'heroTitleEs', label: 'Títol (ES)' },
          { type: 'string', name: 'heroTitleEn', label: 'Títol (EN)' },
          { type: 'string', name: 'heroTitleDe', label: 'Títol (DE)' },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol (DE)', ui: { component: 'textarea' } },
          // ── Santanyí ──
          { type: 'string', name: 'loc1Name', label: 'Nom ubicació 1' },
          { type: 'string', name: 'loc1Address', label: 'Adreça 1', ui: { component: 'textarea' } },
          { type: 'string', name: 'loc1Phone', label: 'Telèfon 1' },
          { type: 'string', name: 'loc1Email', label: 'Email 1' },
          // ── Cala d'Or ──
          { type: 'string', name: 'loc2Name', label: 'Nom ubicació 2' },
          { type: 'string', name: 'loc2Address', label: 'Adreça 2', ui: { component: 'textarea' } },
          { type: 'string', name: 'loc2Phone', label: 'Telèfon 2' },
          { type: 'string', name: 'loc2Email', label: 'Email 2' },
          // ── Social ──
          { type: 'string', name: 'followUsCa', label: 'Segueix-nos (CA)' },
          { type: 'string', name: 'followUsEs', label: 'Segueix-nos (ES)' },
          { type: 'string', name: 'followUsEn', label: 'Segueix-nos (EN)' },
          { type: 'string', name: 'followUsDe', label: 'Segueix-nos (DE)' },
          { type: 'string', name: 'instagramHandle', label: 'Instagram handle' },
          { type: 'string', name: 'instagramUrl', label: 'Instagram URL' },
          { type: 'string', name: 'instagramFollowers', label: 'Seguidors Instagram' },
          { type: 'string', name: 'followersCa', label: 'Etiqueta seguidors (CA)' },
          { type: 'string', name: 'followersEs', label: 'Etiqueta seguidors (ES)' },
          { type: 'string', name: 'followersEn', label: 'Etiqueta seguidors (EN)' },
          { type: 'string', name: 'followersDe', label: 'Etiqueta seguidors (DE)' },
          // ── WhatsApp ──
          // ── Horaris d'obertura ──
          { type: 'string', name: 'scheduleTitleCa', label: 'Títol horaris (CA)' },
          { type: 'string', name: 'scheduleTitleEs', label: 'Títol horaris (ES)' },
          { type: 'string', name: 'scheduleTitleEn', label: 'Títol horaris (EN)' },
          { type: 'string', name: 'scheduleTitleDe', label: 'Títol horaris (DE)' },
          { type: 'string', name: 'weekdaysLabelCa', label: 'Dies laborables (CA)' },
          { type: 'string', name: 'weekdaysLabelEs', label: 'Dies laborables (ES)' },
          { type: 'string', name: 'weekdaysLabelEn', label: 'Dies laborables (EN)' },
          { type: 'string', name: 'weekdaysLabelDe', label: 'Dies laborables (DE)' },
          { type: 'string', name: 'weekdaysHours', label: 'Horari dies laborables' },
          { type: 'string', name: 'saturdayLabelCa', label: 'Dissabte (CA)' },
          { type: 'string', name: 'saturdayLabelEs', label: 'Dissabte (ES)' },
          { type: 'string', name: 'saturdayLabelEn', label: 'Dissabte (EN)' },
          { type: 'string', name: 'saturdayLabelDe', label: 'Dissabte (DE)' },
          { type: 'string', name: 'saturdayHours', label: 'Horari dissabte' },
          { type: 'string', name: 'sundayLabelCa', label: 'Diumenge (CA)' },
          { type: 'string', name: 'sundayLabelEs', label: 'Diumenge (ES)' },
          { type: 'string', name: 'sundayLabelEn', label: 'Diumenge (EN)' },
          { type: 'string', name: 'sundayLabelDe', label: 'Diumenge (DE)' },
          { type: 'string', name: 'sundayHours', label: 'Horari diumenge' },
          // ── Títol formulari ──
          { type: 'string', name: 'formTitleCa', label: 'Títol formulari (CA)' },
          { type: 'string', name: 'formTitleEs', label: 'Títol formulari (ES)' },
          { type: 'string', name: 'formTitleEn', label: 'Títol formulari (EN)' },
          { type: 'string', name: 'formTitleDe', label: 'Títol formulari (DE)' },
          { type: 'string', name: 'formSubtitleCa', label: 'Subtítol formulari (CA)' },
          { type: 'string', name: 'formSubtitleEs', label: 'Subtítol formulari (ES)' },
          { type: 'string', name: 'formSubtitleEn', label: 'Subtítol formulari (EN)' },
          { type: 'string', name: 'formSubtitleDe', label: 'Subtítol formulari (DE)' },
          // ── WhatsApp ──
          { type: 'string', name: 'waLabelCa', label: 'Etiqueta WhatsApp (CA)' },
          { type: 'string', name: 'waLabelEs', label: 'Etiqueta WhatsApp (ES)' },
          { type: 'string', name: 'waLabelEn', label: 'Etiqueta WhatsApp (EN)' },
          { type: 'string', name: 'waLabelDe', label: 'Etiqueta WhatsApp (DE)' },
          { type: 'string', name: 'waMessageCa', label: 'Missatge WhatsApp (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'waMessageEs', label: 'Missatge WhatsApp (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'waMessageEn', label: 'Missatge WhatsApp (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'waMessageDe', label: 'Missatge WhatsApp (DE)', ui: { component: 'textarea' } },
        ],
      },

      // ─── PÀGINES GENERALS (escalable) ────────────────────────────────
      {
        name: 'pagines',
        label: '📄 Pàgines generals',
        path: 'src/content/pagines',
        format: 'json',
        ui: {
          filename: {
            readonly: false,
            slugify: (values: any) =>
              (values?.titleCa || 'pagina')
                .toLowerCase()
                .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
                .replace(/\s+/g, '-')
                .replace(/[^\w-]/g, ''),
          },
        },
        fields: [
          // ── SEO ──────────────────────────────────────────────────────
          { type: 'string', name: 'seoTitleCa', label: '🔍 SEO Títol (CA)' },
          { type: 'string', name: 'seoTitleEs', label: '🔍 SEO Títol (ES)' },
          { type: 'string', name: 'seoTitleEn', label: '🔍 SEO Títol (EN)' },
          { type: 'string', name: 'seoTitleDe', label: '🔍 SEO Títol (DE)' },
          { type: 'string', name: 'seoDescCa',  label: '🔍 SEO Descripció (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'seoDescEs',  label: '🔍 SEO Descripció (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'seoDescEn',  label: '🔍 SEO Descripció (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'seoDescDe',  label: '🔍 SEO Descripció (DE)', ui: { component: 'textarea' } },
          // ── HERO ─────────────────────────────────────────────────────
          {
            type: 'string', name: 'heroBg', label: 'Color fons hero',
            options: [
              { label: 'Blau (principal)',    value: 'blue' },
              { label: 'Porpra (gimnàs)',     value: 'purple' },
              { label: 'Taronja (pàdel)',     value: 'orange' },
              { label: 'Verd',                value: 'green' },
              { label: 'Fosc (piscina)',      value: 'pool' },
            ],
          },
          { type: 'string', name: 'heroBadgeCa',    label: 'Badge hero (CA)' },
          { type: 'string', name: 'heroBadgeEs',    label: 'Badge hero (ES)' },
          { type: 'string', name: 'heroBadgeEn',    label: 'Badge hero (EN)' },
          { type: 'string', name: 'heroBadgeDe',    label: 'Badge hero (DE)' },
          { type: 'string', name: 'heroTitleCa',    label: 'Títol hero (CA)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEs',    label: 'Títol hero (ES)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleEn',    label: 'Títol hero (EN)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'heroTitleDe',    label: 'Títol hero (DE)',    ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleCa', label: 'Subtítol hero (CA)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEs', label: 'Subtítol hero (ES)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleEn', label: 'Subtítol hero (EN)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroSubtitleDe', label: 'Subtítol hero (DE)', ui: { component: 'textarea' } },
          { type: 'string', name: 'heroCtaCa',      label: 'Botó CTA (CA)' },
          { type: 'string', name: 'heroCtaEs',      label: 'Botó CTA (ES)' },
          { type: 'string', name: 'heroCtaEn',      label: 'Botó CTA (EN)' },
          { type: 'string', name: 'heroCtaDe',      label: 'Botó CTA (DE)' },
          { type: 'string', name: 'heroCtaUrl',     label: 'URL botó CTA' },
          // ── CONTINGUT RICH-TEXT ───────────────────────────────────────
          { type: 'rich-text', name: 'contingutCa', label: '📝 Contingut (CA)' },
          { type: 'rich-text', name: 'contingutEs', label: '📝 Contingut (ES)' },
          { type: 'rich-text', name: 'contingutEn', label: '📝 Contingut (EN)' },
          { type: 'rich-text', name: 'contingutDe', label: '📝 Contingut (DE)' },
          // ── CTA FINAL ────────────────────────────────────────────────
          { type: 'string', name: 'ctaTitleCa', label: 'Títol CTA final (CA)' },
          { type: 'string', name: 'ctaTitleEs', label: 'Títol CTA final (ES)' },
          { type: 'string', name: 'ctaTitleEn', label: 'Títol CTA final (EN)' },
          { type: 'string', name: 'ctaTitleDe', label: 'Títol CTA final (DE)' },
          { type: 'string', name: 'ctaBtn1Ca',  label: 'Botó 1 (CA)' },
          { type: 'string', name: 'ctaBtn1Es',  label: 'Botó 1 (ES)' },
          { type: 'string', name: 'ctaBtn1En',  label: 'Botó 1 (EN)' },
          { type: 'string', name: 'ctaBtn1De',  label: 'Botó 1 (DE)' },
          { type: 'string', name: 'ctaBtn1Url', label: 'URL botó 1' },
          { type: 'string', name: 'ctaBtn2Ca',  label: 'Botó 2 (CA)' },
          { type: 'string', name: 'ctaBtn2Es',  label: 'Botó 2 (ES)' },
          { type: 'string', name: 'ctaBtn2En',  label: 'Botó 2 (EN)' },
          { type: 'string', name: 'ctaBtn2De',  label: 'Botó 2 (DE)' },
          { type: 'string', name: 'ctaBtn2Url', label: 'URL botó 2' },
        ],
      },

      // ─── NOTÍCIES ─────────────────────────────────────────────────────
      {
        name: 'noticies',
        label: '📢 Notícies i novetats',
        path: 'src/content/noticies',
        format: 'json',
        ui: {
          filename: {
            readonly: false,
            slugify: (values: any) => values?.titolCa?.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '') || 'noticia',
          },
        },
        fields: [
          { type: 'string',    name: 'titolCa',     label: 'Títol (CA)' },
          { type: 'string',    name: 'titolEs',     label: 'Títol (ES)' },
          { type: 'string',    name: 'titolEn',     label: 'Títol (EN)' },
          { type: 'string',    name: 'titolDe',     label: 'Títol (DE)' },
          { type: 'datetime',  name: 'data',        label: 'Data de publicació' },
          { type: 'image',     name: 'imatge',      label: 'Imatge destacada', uploadDir: () => 'public/images/noticies' },
          { type: 'rich-text', name: 'contingutCa', label: 'Contingut (CA)' },
          { type: 'rich-text', name: 'contingutEs', label: 'Contingut (ES)' },
          { type: 'boolean',   name: 'publicada',   label: 'Publicada' },
        ],
      },

    ],
  },
});
